/*
LeetCode 389: Find the Difference

Problem:
You are given two strings s and t.
String t is generated by randomly shuffling string s and then adding one extra letter at any position.

Return the letter that was added.

Example:
Input: s = "abcd", t = "abcde"
Output: 'e'

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
Both strings contain lowercase English letters.
*/

import java.util.Arrays;

public class FindTheDifference {

    // -------------------------------
    // Brute Force Approach
    // Sort both strings and compare
    // Time Complexity: O(n log n)
    // Space Complexity: O(n)
    // -------------------------------
    public static char bruteForce(String s, String t) {

        char[] sArr = s.toCharArray();
        char[] tArr = t.toCharArray();

        Arrays.sort(sArr);
        Arrays.sort(tArr);

        for (int i = 0; i < sArr.length; i++) {
            if (sArr[i] != tArr[i]) {
                return tArr[i];
            }
        }

        return tArr[tArr.length - 1];
    }


    // -------------------------------
    // Better Approach
    // Use frequency array
    // Time Complexity: O(n)
    // Space Complexity: O(1) (26 letters)
    // -------------------------------
    public static char betterApproach(String s, String t) {

        int[] freq = new int[26];

        for (char c : s.toCharArray()) {
            freq[c - 'a']++;
        }

        for (char c : t.toCharArray()) {
            freq[c - 'a']--;
            if (freq[c - 'a'] < 0) {
                return c;
            }
        }

        return ' ';
    }


    // -------------------------------
    // Optimal Approach
    // XOR operation
    // Time Complexity: O(n)
    // Space Complexity: O(1)
    // -------------------------------
    public static char optimalApproach(String s, String t) {

        int xor = 0;

        for (char c : s.toCharArray()) {
            xor ^= c;
        }

        for (char c : t.toCharArray()) {
            xor ^= c;
        }

        return (char) xor;
    }


    // -------------------------------
    // Main Method (Driver Code)
    // -------------------------------
    public static void main(String[] args) {

        String s = "abcd";
        String t = "abcde";

        System.out.println("Brute Force Result: " + bruteForce(s, t));
        System.out.println("Better Approach Result: " + betterApproach(s, t));
        System.out.println("Optimal Approach Result: " + optimalApproach(s, t));
    }
}